name: Build FTControl Docs
on:
  push:
    branches:
      - main
    paths:
      - lazarkit-website/**
      - test-codebase/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/examples/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

concurrency:
  group: "docs-deploy"
  cancel-in-progress: true

env:
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REPO_FOLDER: compose
  BASE_DIR: lazarkit-website
  SERVICE_FOLDER: /home/ftcontrol-docs
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: myregistry.bylazar.com/ftcontrol-docs

jobs:
  build:
    name: Build and Deploy
    runs-on: lazarvps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ls
        run: ls -a
      - name: Build and Push Docker Image
        run: |
          echo "$SUDO_PASSWORD" | sudo -S bash -c "
            set -e
            sudo docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD myregistry.bylazar.com
            sudo docker build --pull --cache-from $IMAGE_NAME \
              --tag $IMAGE_NAME:$GITHUB_SHA \
              --tag $IMAGE_NAME:latest \
              . -f ./$BASE_DIR/Dockerfile
            sudo docker push $IMAGE_NAME:$GITHUB_SHA
            sudo docker push $IMAGE_NAME:latest
          "

  deploy:
    runs-on: lazarvps
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy and set permissions
        run: |
          echo "$SUDO_PASSWORD" | sudo -S bash -c "
            mkdir -p $SERVICE_FOLDER
            cp -r $REPO_FOLDER/* $SERVICE_FOLDER
          "
      - name: Restart Docker Compose service
        run: |
          echo "$SUDO_PASSWORD" | sudo -S su -c "
            sudo docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD myregistry.bylazar.com
            cd $SERVICE_FOLDER
            docker compose down
            docker compose up -d
          "