name: Redeploy Images
on:
  push:
    branches:
      - main
    paths:
      - compose/**
      - .github/workflows/deploy-compose.yml
  workflow_dispatch:

concurrency:
  group: "compose-deploy"
  cancel-in-progress: true

env:
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  SERVICE_FOLDER: /home/ftcontrol-docs
  REPO_FOLDER: compose

jobs:
  deploy:
    runs-on: lazarvps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: compose
          sparse-checkout-cone-mode: false

      - name: Copy and set permissions
        run: |
          echo "$SUDO_PASSWORD" | sudo -S bash -c "
            mkdir -p $SERVICE_FOLDER
            cp -r $REPO_FOLDER/* $SERVICE_FOLDER
          "
      - name: Restart Docker Compose service
        run: |
          echo "$SUDO_PASSWORD" | sudo -S su -c "
            sudo docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD myregistry.bylazar.com
            cd $SERVICE_FOLDER
            docker compose up -d
          "